- name: Get proxy domain
  shell: oc get ingress.config cluster -o jsonpath='{.spec.domain}'
  register: PROXY_DOMAIN_OUTPUT

- name: Set proxy domain
  set_fact:
    PROXY_DOMAIN: "{{ PROXY_DOMAIN_OUTPUT.stdout }}"

- name: Create a route to the API
  kubernetes.core.k8s:
    template: ./templates/route.j2
    state: present
  # wait_for:
  #   timeout: 5 

- name: Wait for route to the API
  uri:
    url: "https://asm-svt-{{ NAMESPACE }}.{{ PROXY_DOMAIN }}/1.0/rest-observer/service/info"
    method: GET
  register: OUTPUT
  retries: 80
  delay: 120
  # until: OUTPUT.status == 200
  until: (OUTPUT.status == 200) and ('"OK" in OUTPUT.msg')

- name: Get and set credentials for OS other than MacOSX
  block:
    - name: Get password
      shell: oc get secret aiops-topology-asm-credentials -n "{{ NAMESPACE }}" -o yaml | grep password | cut -d ':' -f2 | base64 -di | tr -cd '[:print:]'
      register: PASSWORD_OUTPUT

    - name: Set password
      set_fact:
        PASSWORD: "{{ PASSWORD_OUTPUT.stdout }}"
        
    - name: Get username
      shell: oc get secret aiops-topology-asm-credentials -n "{{ NAMESPACE }}" -o yaml | grep username | cut -d ':' -f2 | base64 -di | tr -cd '[:print:]'
      register: USERNAME_OUTPUT

    - name: Set username
      set_fact:
        USERNAME: "{{ USERNAME_OUTPUT.stdout }}"
  when: ansible_distribution != "MacOSX"

- name: Get and set credentials for MacOSX
  block:
    - name: Get password
      shell: oc get secret aiops-topology-asm-credentials -n "{{ NAMESPACE }}" -o yaml | grep password | cut -d ':' -f2 | base64 -d | tr -cd '[:print:]'
      register: PASSWORD_OUTPUT

    - name: Set password
      set_fact:
        PASSWORD: "{{ PASSWORD_OUTPUT.stdout }}"
        
    - name: Get username
      shell: oc get secret aiops-topology-asm-credentials -n "{{ NAMESPACE }}" -o yaml | grep username | cut -d ':' -f2 | base64 -d | tr -cd '[:print:]'
      register: USERNAME_OUTPUT

    - name: Set username
      set_fact:
        USERNAME: "{{ USERNAME_OUTPUT.stdout }}"
  when: ansible_distribution == "MacOSX"
    
- name: Create a Rest Observer bulk-replace job
  uri:
    url: "https://asm-svt-{{ NAMESPACE }}.{{ PROXY_DOMAIN }}/1.0/rest-observer/jobs/bulk_replace"
    user: "{{ USERNAME }}"
    password: "{{ PASSWORD }}"
    method: POST
    body: "{{ lookup('file','files/rest-observer.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255
    status_code: 201