- name: Create robot-shop namespace
  kubernetes.core.k8s:
    src: ./files/namespace.yaml
    state: present
    
- name: Create robot-shop security context 
  shell: |
    oc adm policy add-scc-to-user anyuid -z default -n robot-shop
    oc adm policy add-scc-to-user privileged -z default -n robot-shop

- name: Check if robot-shop helm chart
  shell: helm -n robot-shop history robot-shop
  register: OUTPUT
  ignore_errors: true

- name: Deploy robot-shop helm chart
  shell: helm install robot-shop --namespace robot-shop ./roles/deploy-robot-shop-application/files/helm
  when: '"Install complete" not in OUTPUT.stdout'