# <name> is the name that you want your AI Manager instance to be called.
# <namespace> is the project (namespace) that you want to create the AI Manager instance in. Use the project (namespace) that you created earlier in Create a custom project (namespace).
# <license_acceptance> - set to true to agree to the license terms.
# <proxy_flag> - if you are installing AI Manager online then set to false. If you are installing AI Manager offline, (you used the instructions in Preparing to install IBM Cloud Pak for Watson AIOps in an air-gapped environment), then set to true.
# <proxy_url> - if you are installing AI Manager online then leave this field empty. If you are installing AI Manager offline in an air gapped environment (you used the instructions in Preparing to install IBM Cloud Pak for Watson AIOps in an air-gapped environment), then specify the hostname and port of the proxy server that you have set up to route data from your air gapped environment to external Slack connections. Use the format host:port.
# <size> is the size that you require for your AI Manager installation. For more information, see Sizing.
# <storage_class_name> is the storage class that you want to use. If the storage provider for your deployment is Red Hat OpenShift Data Foundation, previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-cephfs. For more information, see Storage considerations.
# <large_block_storage_class_name> If the storage provider for your deployment is Red Hat OpenShift Data Foundation, previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-ceph-rbd. For more information, see Storage considerations.
# <imagePullSecret> - The IBM entitlement key for key that you created in the step Create the entitlement key secret. This value needs to be ibm-entitlement-key. If you are installing AI Manager offline in an air gapped environment, leave this field empty.

NAMESPACE: aiops
ENTITLED_REGISTRY: cp.icr.io
ENTITLED_REGISTRY_USER: cp
SUBSCRIPTION_CHANNEL: v3.3
WAIOPS_NAME: ibm-aiops
LICENSE_ACCEPTANCE: true
PROXY_FLAG: false
PROXY_URL: 
WAIOPS_SIZE: small
STORAGECLASS_FILE: ibmc-file-gold-gid
STORAGECLASS_BLOCK: ibmc-file-gold-gid

GUEST_USERNAME: guest
GUEST_PASSWORD: gu357_p@55
GUEST_EMAIL: example@example.com
GUEST_DISPLAY_NAME: guest
GUEST_ROLES: zen_administrator_role
CP4WAIOPS_PORT: 443
ADMIN_USERNAME: admin