---
apiVersion: v1
kind: Namespace
metadata:
  name: aiops
  labels:
    name: application-optimization-accelerator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-optimization-accelerator
  namespace: aiops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: application-optimization-accelerator
subjects:
  - kind: ServiceAccount
    name: application-optimization-accelerator
    namespace: aiops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: application-optimization-accelerator
  namespace: aiops
spec:
  template:
    spec:
      containers:
      - name: application-optimization-accelerator
        image: quay.io/nate_malone_ibm/application-optimization-accelerator:latest
        command: ["ansible-playbook",  "install-ai-manager.yaml"]
        args: ["-vvvvv"]
        # command: ["tail"]
        # args: ["-f", "/dev/null"]
      serviceAccount: application-optimization-accelerator
      restartPolicy: Never
      imagePullPolicy: Always
  backoffLimit: 2